# Ultralytics ğŸš€ AGPL-3.0 License - https://ultralytics.com/license

# æ¨ç†æ¨¡å‹
model:
  # path: r"./jg_project/car_vis/epoch120_v1/weights/best.pt"
  path: "/home/sk/project/jg_project/cls/test3/weights/best.pt"
# è¾“å…¥è§†é¢‘/è§†é¢‘æµåœ°å€
input:
  # source: "./datasets/test-video/test0/mp4/343205-202507201624-202507201629.mp4"
  source: "/home/sk/project/inference_results/cropped_bus"
# è¾“å‡ºè·¯å¾„
output:
  path: "./inference_results/classified_images"
# ä»»åŠ¡ç±»å‹ï¼š
#    crop_imageï¼šè£å‰ªå›¾åƒ
#    draw_image: ç»˜åˆ¶å›¾åƒ
#    save_video: ä¿å­˜è§†é¢‘
task:
  type: "draw_image"
# ç›®æ ‡ç±»åˆ«ID
target_class_id: [1]

# æ¨ç†è®¾ç½®
infer_setting:
  # è®¾å¤‡
  device: "7"
  # ç½®ä¿¡åº¦é˜ˆå€¼
  confidence_threshold: 0.5
