# Ultralytics ğŸš€ AGPL-3.0 License - https://ultralytics.com/license

# predict-detecté…ç½®æ–‡ä»¶
# æ¨¡å‹ç›¸å…³é…ç½®
model:
  # æ¨¡å‹æ–‡ä»¶çš„è·¯å¾„ï¼ŒæŒ‡å®šè¦ä½¿ç”¨çš„é¢„è®­ç»ƒæ¨¡å‹æ–‡ä»¶ä½ç½®
  path: "./jg_project/v001-epoch100-aug/weights/best.pt"
  # æ¨ç†æ—¶ä½¿ç”¨çš„è®¾å¤‡ï¼Œ'0' è¡¨ç¤ºä½¿ç”¨ç¬¬ä¸€ä¸ª GPUï¼Œ'cpu' è¡¨ç¤ºä½¿ç”¨ CPU
  device: "1"

# è¾“å…¥æºé…ç½®
input:
  # è¾“å…¥æ•°æ®çš„æºåœ°å€ï¼Œå¯ä»¥æ˜¯æ–‡ä»¶è·¯å¾„ã€æ‘„åƒå¤´ç´¢å¼•æˆ– RTSP æµåœ°å€
  source: "rtsp://localhost:8556/test-crop"
  # source: './datasets/test-video/mp4/343205-202507201624-202507201629.mp4'

# æ£€æµ‹ç›®æ ‡é…ç½®
detection:
  # æŒ‡å®šè¦æ£€æµ‹çš„ç›®æ ‡ç±»åˆ«åç§°
  target_class: "bus"
  # æ£€æµ‹ç½®ä¿¡åº¦é˜ˆå€¼ï¼Œåªæœ‰ç½®ä¿¡åº¦é«˜äºæ­¤å€¼çš„æ£€æµ‹ç»“æœæ‰ä¼šè¢«ä¿ç•™
  confidence_threshold: 0.45

# è¾“å‡ºé…ç½®
output:
  # æ£€æµ‹ç»“æœä¿å­˜çš„ç›®å½•è·¯å¾„
  save_directory: "./inference_results/test/bus_crops_from_rtsp"
  # æ˜¯å¦æ˜¾ç¤ºæ£€æµ‹ç»“æœçš„çª—å£ï¼Œtrue è¡¨ç¤ºæ˜¾ç¤ºï¼Œfalse è¡¨ç¤ºä¸æ˜¾ç¤º
  display_window: false
